# Generated by Django 4.2.2 on 2023-06-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='ISBN',
            field=models.CharField(default='Null', max_length=25, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='salutation',
            field=models.CharField(choices=[('Prof', 'Professor'), ('Dr', 'Doctor'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms')], max_length=5),
        ),
    ]
