# Generated by Django 4.2.2 on 2023-06-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_author_name_author_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
