# Generated by Django 4.2.2 on 2023-06-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_books_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='no_of_books',
            field=models.IntegerField(default=1),
        ),
    ]
