# Generated by Django 4.2.2 on 2023-06-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_books_no_of_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('late_return_rate', models.IntegerField(default=0, help_text='rate of the initial charge per day')),
                ('max_borrow_fee_limit', models.DecimalField(decimal_places=2, default=500.0, max_digits=16)),
            ],
        ),
        migrations.AddField(
            model_name='bookissued',
            name='total_pending_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='books',
            name='no_of_reserve_books',
            field=models.IntegerField(default=1),
        ),
    ]
