# Generated by Django 4.2.2 on 2023-06-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_bookfees_bookissued_total_pending_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissued',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
