# Generated by Django 4.2.2 on 2023-06-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_bookissued_return_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='ISBN',
            new_name='isbn',
        ),
    ]
