# Generated by Django 4.2.2 on 2023-06-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_rename_isbn_books_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookissued',
            old_name='total_pending_fee',
            new_name='total_fee',
        ),
        migrations.AlterField(
            model_name='author',
            name='salutation',
            field=models.CharField(choices=[('Prof.', 'Professor'), ('Dr.', 'Doctor'), ('Mr.', 'Mr'), ('Mrs.', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms')], max_length=5),
        ),
    ]
