# Generated by Django 4.2.2 on 2023-06-13 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_transactiontype_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='name',
        ),
    ]
