# Generated by Django 4.2.2 on 2023-06-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_transaction_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
