# Generated by Django 4.2.2 on 2023-06-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_transaction_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source_ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
