# Generated by Django 4.2.2 on 2023-07-03 23:20

import base.backend.utils.utilities
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_transaction_source_ip_transaction_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(default=base.backend.utils.utilities.create_token, max_length=200)),
                ('expires_at', models.DateTimeField(default=base.backend.utils.utilities.token_expiry)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Identities',
                'ordering': ('-date_created',),
            },
        ),
    ]
