# Generated by Django 4.2.2 on 2023-06-12 10:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('national_id', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=2)),
                ('membership_no', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
