# Generated by Django 4.2.2 on 2023-06-12 12:20

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('members', '0002_members_state_alter_members_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='state',
            field=models.ForeignKey(default=base.models.State.default_state, on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
    ]
