# Generated by Django 4.2.2 on 2023-06-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_members_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='membership_no',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='national_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
