# Generated by Django 4.2.2 on 2023-06-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_members_membership_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='membership_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
